name: Manual Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Release version (e.g., v1.0.0)"
        required: true
        type: string
      prerelease:
        description: "Mark as pre-release?"
        required: false
        default: false
        type: boolean

jobs:
  create-release:
    runs-on: ubuntu-latest
    name: Create GitHub Release

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set version variables
        id: version
        run: |
          VERSION="${{ github.event.inputs.version }}"
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "version_number=${VERSION#v}" >> $GITHUB_OUTPUT
          echo "Release version: $VERSION"

      - name: Update About.xml version
        run: |
          VERSION_NUMBER="${{ steps.version.outputs.version_number }}"
          echo "📝 Updating About.xml with version $VERSION_NUMBER"

          if grep -q "<version>" About/About.xml; then
            sed -i "s|<version>.*</version>|<version>$VERSION_NUMBER</version>|" About/About.xml
          else
            sed -i "/<packageId>Felix.BeautifullOdyssey<\/packageId>/a\\    <version>$VERSION_NUMBER</version>" About/About.xml
          fi

          echo "✓ About.xml updated"

      - name: Create mod package
        run: |
          echo "📦 Creating mod package..."

          mkdir -p release/BeautifullOdyssey

          cp -r About/ release/BeautifullOdyssey/
          cp -r Patches/ release/BeautifullOdyssey/
          cp README.md release/BeautifullOdyssey/
          cp LICENSE release/BeautifullOdyssey/ 2>/dev/null || echo "No LICENSE file found"

          cd release
          zip -r BeautifullOdyssey-${{ steps.version.outputs.version }}.zip BeautifullOdyssey/
          cd ..

          echo "✓ Mod package created: BeautifullOdyssey-${{ steps.version.outputs.version }}.zip"

      - name: Generate changelog
        id: changelog
        run: |
          echo "📋 Generating changelog..."

          PREV_TAG=$(git describe --tags --abbrev=0 HEAD^ 2>/dev/null || echo "")

          if [ -n "$PREV_TAG" ]; then
            echo "📅 Changes since $PREV_TAG:"
            CHANGELOG=$(git log --pretty=format:"- %s" $PREV_TAG..HEAD)
          else
            echo "📅 Initial release"
            CHANGELOG="Initial release of BeautifullOdyssey mod"
          fi

          cat > CHANGELOG.md << EOF
          # BeautifullOdyssey ${{ steps.version.outputs.version }}

          ## What's Changed

          $CHANGELOG

          ## Features

          This mod transforms ugly Odyssey DLC buildings into beautiful ones:

          | Building | Old Beauty | New Beauty |
          |----------|------------|------------|
          | **GravEngine** | -10 | +10 |
          | **GravshipShieldGenerator** | -10 | +10 |
          | **GravFieldExtender** | -10 | +10 |
          | **SignalJammer** | -10 | +10 |
          | **PilotSubpersonaCore** | -10 | +10 |
          | **GravAnchor** | -10 | +10 |
          | **GravcorePowerCell** | -5 | +5 |

          ## Installation

          1. Download the \`BeautifullOdyssey-${{ steps.version.outputs.version }}.zip\` file
          2. Extract to your RimWorld/Mods folder
          3. Enable in mod manager (requires Odyssey DLC)

          ## Compatibility

          - **Requires**: RimWorld 1.6 + Odyssey DLC
          - **Compatible with**: Most other mods
          - **Load Order**: After Odyssey DLC
          EOF

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.version.outputs.version }}
          name: BeautifullOdyssey ${{ steps.version.outputs.version }}
          body_path: CHANGELOG.md
          files: |
            release/BeautifullOdyssey-${{ steps.version.outputs.version }}.zip
          prerelease: ${{ github.event.inputs.prerelease == 'true' }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit version update
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add About/About.xml
          git commit -m "chore: bump version to ${{ steps.version.outputs.version }}" || exit 0
          git push origin main

      - name: Success notification
        run: |
          echo "🎉 Release ${{ steps.version.outputs.version }} created successfully!"
          echo "📦 Download: https://github.com/${{ github.repository }}/releases/latest"
